### ISSUE TITLE
用户稳定进入灰度组，前端如何实现

### ISSUE THREAD

**Issue by Yill625** [FeatureProbe/client-sdk-react#36]
[用户稳定进入灰度组文档](https://docs.featureprobe.com/zh-CN/tutorials/rollout_tutorial/stable_rollout_tutorial)

只提供了后端方式

```js
const user = new featureProbe.FPUser().stableRollout(i.toString());
const isOpen = fpClient.booleanValue(YOUR_TOGGLE_KEY, user, false);
```
前端尝试 boolValue 函数加第二个参数控制用户进去同一组失败，刷新还是按照流量随机进入A/B组

<img width="1344" alt="image" src="https://github.com/FeatureProbe/client-sdk-react/assets/25902472/5f19e14a-141b-49bf-a206-4e8e5d99ae68">

![2024-02-21 19 25 06](https://github.com/FeatureProbe/client-sdk-react/assets/25902472/1399df62-a950-43b8-9f5b-de7010aa21cc)

**Comment by frankzhaopeng** [comment]
在初始化react sdk的时候传入的user对象，通过new FPUser方法初始化时，可以传入你代码中从cookie中获取的uid。
`const uid = xxx;`
`const user = new FPUser(user);`
这样user会稳定进入一个实验组。
另外，boolValue的第二个参数是获取开关时的默认返回值，不能用于设置user变量。
具体可参考js sdk的api：https://featureprobe.github.io/client-sdk-js/index.html

**Comment by Yill625** [comment]
@frankzhaopeng 感谢，这个已经解决了。
这边还有一个问题：指标分析没有接收到数据
<img width="1690" alt="image" src="https://github.com/FeatureProbe/client-sdk-react/assets/25902472/7ba28864-73f6-403e-a22f-0ad0cfa5a8cb">

但是在H5已经看到接口有传递自定义事件了
<img width="1935" alt="image" src="https://github.com/FeatureProbe/client-sdk-react/assets/25902472/adc1af78-1f36-4ea6-9528-d8ee484b5847">

<img width="822" alt="image" src="https://github.com/FeatureProbe/client-sdk-react/assets/25902472/0c41b6be-e27f-4913-88b0-9be837727232">
打开事件追踪器，可以看到开关事件是已经生效的了，但是指标事件并没有数据
<img width="1919" alt="image" src="https://github.com/FeatureProbe/client-sdk-react/assets/25902472/d91dbe84-ffdd-4ee3-9629-818aa7729275">

**Comment by frankzhaopeng** [comment]
目前SaaS服务不再维护，请自己搭建服务使用该功能。
